export class PackageError extends Error {
  constructor(code, message, extra = {}) {
    super(message || code)
    this.name = 'PackageError'
    this.code = code
    this.extra = extra
  }
}

export const PACKAGE_ERROR = {
  PROPERTY_LIMIT_EXCEEDED: 'PROPERTY_LIMIT_EXCEEDED',
  PACKAGE_VERSION_IMMUTABLE: 'PACKAGE_VERSION_IMMUTABLE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  PACKAGE_VERSION_NOT_FOUND: 'PACKAGE_VERSION_NOT_FOUND',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  VERSION_NOT_PUBLISHED: 'VERSION_NOT_PUBLISHED',
  ACTIVE_SUBSCRIPTION_EXISTS: 'ACTIVE_SUBSCRIPTION_EXISTS',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',
  UNKNOWN_CADENCE: 'UNKNOWN_CADENCE',
  APPROVAL_SELF_APPROVAL_FORBIDDEN: 'APPROVAL_SELF_APPROVAL_FORBIDDEN',
  APPROVAL_ALREADY_RESOLVED: 'APPROVAL_ALREADY_RESOLVED',
  APPROVAL_NOT_FOUND: 'APPROVAL_NOT_FOUND',
  PUBLISH_REQUIRES_APPROVAL: 'PUBLISH_REQUIRES_APPROVAL',
  REASON_REQUIRED: 'REASON_REQUIRED',
  DRAFT_ONLY: 'DRAFT_ONLY',
  FEATURE_NOT_FOUND: 'FEATURE_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  ECONOMICS_PATCH_FORBIDDEN: 'ECONOMICS_PATCH_FORBIDDEN',
  CANCEL_IMMEDIATE_APPROVAL_REQUIRED: 'CANCEL_IMMEDIATE_APPROVAL_REQUIRED',
}

export const PACKAGE_HTTP_STATUS = {
  [PACKAGE_ERROR.PROPERTY_LIMIT_EXCEEDED]: 409,
  [PACKAGE_ERROR.PACKAGE_VERSION_IMMUTABLE]: 409,
  [PACKAGE_ERROR.INVALID_TRANSITION]: 409,
  [PACKAGE_ERROR.SUBSCRIPTION_NOT_FOUND]: 404,
  [PACKAGE_ERROR.PACKAGE_VERSION_NOT_FOUND]: 404,
  [PACKAGE_ERROR.PACKAGE_NOT_FOUND]: 404,
  [PACKAGE_ERROR.VERSION_NOT_PUBLISHED]: 409,
  [PACKAGE_ERROR.ACTIVE_SUBSCRIPTION_EXISTS]: 409,
  [PACKAGE_ERROR.NO_ACTIVE_SUBSCRIPTION]: 409,
  [PACKAGE_ERROR.UNKNOWN_CADENCE]: 400,
  [PACKAGE_ERROR.APPROVAL_SELF_APPROVAL_FORBIDDEN]: 403,
  [PACKAGE_ERROR.APPROVAL_ALREADY_RESOLVED]: 409,
  [PACKAGE_ERROR.APPROVAL_NOT_FOUND]: 404,
  [PACKAGE_ERROR.PUBLISH_REQUIRES_APPROVAL]: 409,
  [PACKAGE_ERROR.REASON_REQUIRED]: 400,
  [PACKAGE_ERROR.DRAFT_ONLY]: 409,
  [PACKAGE_ERROR.FEATURE_NOT_FOUND]: 404,
  [PACKAGE_ERROR.INVALID_INPUT]: 400,
  [PACKAGE_ERROR.ECONOMICS_PATCH_FORBIDDEN]: 400,
  [PACKAGE_ERROR.CANCEL_IMMEDIATE_APPROVAL_REQUIRED]: 202,
}
