export class PackageError extends Error {
  constructor(code, message, extra = {}) {
    super(message || code)
    this.name = 'PackageError'
    this.code = code
    this.extra = extra
  }
}

export const PACKAGE_ERROR = {
  PROPERTY_LIMIT_EXCEEDED: 'PROPERTY_LIMIT_EXCEEDED',
  PACKAGE_VERSION_IMMUTABLE: 'PACKAGE_VERSION_IMMUTABLE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  PACKAGE_VERSION_NOT_FOUND: 'PACKAGE_VERSION_NOT_FOUND',
  VERSION_NOT_PUBLISHED: 'VERSION_NOT_PUBLISHED',
  ACTIVE_SUBSCRIPTION_EXISTS: 'ACTIVE_SUBSCRIPTION_EXISTS',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',
  UNKNOWN_CADENCE: 'UNKNOWN_CADENCE',
}
