/**
 * English copy for AGT-APR-004 / AGT-APR-005 submitters.
 * Arabic slots marked [TRANSLATION-PENDING] where i18n mirrors are needed.
 */

export const badComparableCopy = {
  pageTitle: 'Report a bad comparable',
  modalTitle: 'Report this comparable',
  closeAria: 'Cancel report',
  pickerLabel: 'Which comparable are you reporting?',
  pickerPlaceholder: 'Search by address, portal-ID, or agent…',
  comparableIdLabel: 'Comparable ID',
  comparableIdPlaceholder: 'cmp_… or listing id',
  comparableTypeLabel: 'Comparable type',
  reasonLabel: 'Why are you reporting this?',
  notesLabel: 'Tell PA what happened',
  notesPlaceholder: 'Share what you saw. Kind and specific beats terse.',
  notesTooShort: 'Add a bit more detail so PA can act on it.',
  notesTooLong: 'Explanation is too long — trim it to 1000 characters.',
  evidenceLabel: 'Evidence (optional, up to 3 files)',
  evidenceHelper: "Screenshots or PDFs make PA's job faster.",
  confidenceLabel: 'How confident are you?',
  confidenceSelf: 'I saw this myself',
  confidenceHearsay: 'Colleague told me',
  confidenceEvidence: 'I have hard evidence',
  submitIdle: 'Submit report',
  submitBusy: 'Sending…',
  cancel: 'Cancel',
  successLabel: 'Report received — under PA review',
  successSla: 'Typical review: 3 days',
  successBody:
    'Thanks. PA will review your report and let you know the outcome on your inbox.',
  successPrimary: 'View my reports',
  successSecondary: 'Close',
  networkError: "Couldn't send report — check your connection and try again.",
  comparableRequired: 'Pick a comparable before submitting.',
  reasonRequired: 'Pick a reason first.',
  waitingUploads: 'Waiting for uploads to finish…',
  arPending: '[TRANSLATION-PENDING]',
} as const

export const priceReportCopy = {
  heroHeading: 'Submit a price report',
  heroSubheading:
    'Your expert take on market pricing, reviewed by PA and published to your public profile.',
  proBadge: 'Pro feature',
  sectionSubject: '1. Subject',
  sectionSubjectHelper: 'What is this report about?',
  subjectProperty: 'Specific property',
  subjectExternal: 'External / off-platform sale',
  propertyIdLabel: 'Listing ID',
  propertyIdPlaceholder: 'Select or paste a listing id…',
  externalTitleLabel: 'Property title',
  externalLocationLabel: 'Location',
  changeSubject: 'Change',
  sectionRecommendation: '2. Recommendation',
  sectionRecommendationHelper: 'What sold-price evidence are you reporting?',
  currencyLabel: 'Currency',
  amountLabel: 'Sold price',
  soldDateLabel: 'Completion date',
  sectionRationale: '3. Rationale',
  sectionRationaleHelper: 'What supports your recommendation?',
  notesLabel: 'Evidence notes',
  notesPlaceholder:
    'Explain your reasoning. What does the data show that the raw price alone misses?',
  notesTooShort: 'Editorial reports need more depth — add at least a short paragraph.',
  notesTooLong: 'Notes are too long — trim them to 3000 characters.',
  sectionPublication: '4. Publication',
  sectionPublicationHelper: 'How should PA handle review?',
  evidenceLabel: 'Evidence (optional, up to 5 files)',
  evidenceHelper:
    'Attach the data behind your analysis — CSVs, developer decks, sold-price screenshots. PA reviews faster with sources they can verify.',
  submitIdle: 'Submit for PA review',
  submitBusy: 'Sending to PA…',
  saveDraft: 'Save as draft',
  autosaveHelper: 'Your draft autosaves every 30 seconds.',
  successLabel: 'Report received — under PA editorial review',
  successSla: 'Typical editorial review: 48 hours',
  successBody:
    'Thanks. PA will review your report and let you know the outcome on your inbox.',
  successPrimary: 'View my reports',
  successSecondary: 'Start another report',
  upsellHeading: 'Price reports are a Pro feature',
  upsellBody:
    'Establish yourself as a market voice — Pro-tier agents publish price analyses to their public profile with WingCaster\'s editorial team.',
  upsellBullet1: 'Publish to your public agent profile.',
  upsellBullet2: 'WingCaster editorial team review.',
  upsellBullet3: 'Featured on Bazaar consumer surfaces.',
  upsellPrimary: 'See Pro plans',
  upsellSecondary: 'Learn more',
  networkError: "Couldn't save — check your connection and try again.",
  amountRequired: 'Enter a sold price greater than zero.',
  subjectRequired: 'Pick a subject before submitting.',
  waitingUploads: 'Waiting for uploads to finish…',
  featureDisabledToast: 'This feature requires a Pro-tier subscription.',
  arPending: '[TRANSLATION-PENDING]',
} as const
