/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-lc-mode="dark"]'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--lc-font-ui)'],
        display: ['var(--lc-font-display)'],
        mono: ['var(--lc-font-mono)'],
      },
      minHeight: {
        tap: 'var(--lc-tap-target-min)',
      },
      minWidth: {
        tap: 'var(--lc-tap-target-min)',
      },
      height: {
        tap: 'var(--lc-tap-target-min)',
      },
      width: {
        tap: 'var(--lc-tap-target-min)',
      },
      borderRadius: {
        sm: 'var(--lc-radius-sm)',
        md: 'var(--lc-radius-md)',
        lg: 'var(--lc-radius-lg)',
        xl: 'var(--lc-radius-xl)',
        pill: 'var(--lc-radius-pill)',
      },
      boxShadow: {
        sm: 'var(--lc-elevation-sm)',
        md: 'var(--lc-elevation-md)',
        lg: 'var(--lc-elevation-lg)',
      },
      zIndex: {
        base: 'var(--lc-z-base)',
        raised: 'var(--lc-z-raised)',
        sticky: 'var(--lc-z-sticky)',
        dropdown: 'var(--lc-z-dropdown)',
        overlay: 'var(--lc-z-overlay)',
        modal: 'var(--lc-z-modal)',
        toast: 'var(--lc-z-toast)',
        tooltip: 'var(--lc-z-tooltip)',
      },
      transitionDuration: {
        instant: 'var(--lc-duration-instant)',
        fast: 'var(--lc-duration-fast)',
        base: 'var(--lc-duration-base)',
        slow: 'var(--lc-duration-slow)',
        deliberate: 'var(--lc-duration-deliberate)',
      },
      transitionTimingFunction: {
        out: 'var(--lc-easing-out)',
        'in-out': 'var(--lc-easing-in-out)',
        emphasis: 'var(--lc-easing-emphasis)',
      },
      colors: {
        border: 'var(--lc-border)',
        'border-strong': 'var(--lc-border-strong)',
        input: 'var(--lc-border-strong)',
        ring: 'var(--lc-focus-ring)',
        background: 'var(--lc-bg-page)',
        foreground: 'var(--lc-text-primary)',
        heading: 'var(--lc-text-heading)',
        brand: 'var(--lc-text-brand)',
        page: 'var(--lc-bg-page)',
        surface: {
          DEFAULT: 'var(--lc-surface)',
          raised: 'var(--lc-surface-raised)',
          sunken: 'var(--lc-surface-sunken)',
          inverse: 'var(--lc-surface-inverse)',
        },
        sunken: 'var(--lc-surface-sunken)',
        inverse: 'var(--lc-text-inverse)',
        card: {
          DEFAULT: 'var(--lc-surface-raised)',
          foreground: 'var(--lc-text-primary)',
        },
        popover: {
          DEFAULT: 'var(--lc-surface-raised)',
          foreground: 'var(--lc-text-primary)',
        },
        primary: {
          DEFAULT: 'var(--lc-action-primary)',
          foreground: 'var(--lc-action-primary-text)',
          hover: 'var(--lc-action-primary-hover)',
          scrim: 'var(--lc-action-primary-scrim)',
          faint: 'color-mix(in srgb, var(--lc-action-primary) 12%, transparent)',
        },
        secondary: {
          DEFAULT: 'var(--lc-action-secondary)',
          foreground: 'var(--lc-action-secondary-text)',
        },
        muted: {
          DEFAULT: 'var(--lc-surface-sunken)',
          foreground: 'var(--lc-text-muted)',
        },
        accent: {
          DEFAULT: 'var(--lc-action-secondary)',
          foreground: 'var(--lc-action-secondary-text)',
          signal: 'var(--lc-accent)',
          bold: 'var(--lc-accent-bold)',
          edge: 'var(--lc-accent-bold-edge)',
        },
        destructive: {
          DEFAULT: 'var(--lc-status-unpublished-fg)',
          foreground: 'var(--lc-text-inverse)',
        },
        /* Map leftover Tailwind palette names onto status tokens so
           existing green/red/amber utilities follow the mode switch. */
        green: {
          50: 'var(--lc-status-published-bg)',
          100: 'var(--lc-status-published-bg)',
          200: 'var(--lc-status-published-bg)',
          300: 'var(--lc-status-published-dot)',
          400: 'var(--lc-status-published-dot)',
          500: 'var(--lc-status-published-dot)',
          600: 'var(--lc-status-published-fg)',
          700: 'var(--lc-status-published-fg)',
          800: 'var(--lc-status-published-fg)',
          900: 'var(--lc-status-published-fg)',
        },
        red: {
          50: 'var(--lc-status-unpublished-bg)',
          100: 'var(--lc-status-unpublished-bg)',
          200: 'var(--lc-status-unpublished-bg)',
          300: 'var(--lc-status-unpublished-dot)',
          400: 'var(--lc-status-unpublished-dot)',
          500: 'var(--lc-status-unpublished-dot)',
          600: 'var(--lc-status-unpublished-fg)',
          700: 'var(--lc-status-unpublished-fg)',
          800: 'var(--lc-status-unpublished-fg)',
          900: 'var(--lc-status-unpublished-fg)',
        },
        amber: {
          50: 'var(--lc-status-underOffer-bg)',
          100: 'var(--lc-status-underOffer-bg)',
          200: 'var(--lc-status-underOffer-bg)',
          300: 'var(--lc-status-underOffer-dot)',
          400: 'var(--lc-status-underOffer-dot)',
          500: 'var(--lc-status-underOffer-dot)',
          600: 'var(--lc-status-underOffer-fg)',
          700: 'var(--lc-status-underOffer-fg)',
          800: 'var(--lc-status-underOffer-fg)',
          900: 'var(--lc-status-underOffer-fg)',
        },
        yellow: {
          50: 'var(--lc-status-underOffer-bg)',
          100: 'var(--lc-status-underOffer-bg)',
          200: 'var(--lc-status-underOffer-bg)',
          300: 'var(--lc-status-underOffer-dot)',
          400: 'var(--lc-status-underOffer-dot)',
          500: 'var(--lc-status-underOffer-dot)',
          600: 'var(--lc-status-underOffer-fg)',
          700: 'var(--lc-status-underOffer-fg)',
          800: 'var(--lc-status-underOffer-fg)',
          900: 'var(--lc-status-underOffer-fg)',
        },
        purple: {
          50: 'var(--lc-status-closed-bg)',
          100: 'var(--lc-status-closed-bg)',
          200: 'var(--lc-status-closed-bg)',
          500: 'var(--lc-status-closed-dot)',
          600: 'var(--lc-status-closed-fg)',
          700: 'var(--lc-status-closed-fg)',
        },
        violet: {
          50: 'var(--lc-status-closed-bg)',
          600: 'var(--lc-status-closed-fg)',
          700: 'var(--lc-status-closed-fg)',
        },
        slate: {
          50: 'var(--lc-surface-sunken)',
          100: 'var(--lc-surface-sunken)',
          200: 'var(--lc-border)',
          300: 'var(--lc-border-strong)',
          400: 'var(--lc-text-muted)',
          500: 'var(--lc-text-muted)',
          600: 'var(--lc-text-secondary)',
          700: 'var(--lc-text-primary)',
          800: 'var(--lc-text-heading)',
          900: 'var(--lc-surface-inverse)',
        },
        gray: {
          50: 'var(--lc-surface-sunken)',
          100: 'var(--lc-surface-sunken)',
          200: 'var(--lc-border)',
          300: 'var(--lc-border-strong)',
          400: 'var(--lc-text-muted)',
          500: 'var(--lc-text-muted)',
          600: 'var(--lc-text-secondary)',
          700: 'var(--lc-text-primary)',
          800: 'var(--lc-text-heading)',
          900: 'var(--lc-surface-inverse)',
        },
        blue: {
          50: 'color-mix(in srgb, var(--lc-accent) 12%, transparent)',
          100: 'color-mix(in srgb, var(--lc-accent) 16%, transparent)',
          200: 'var(--lc-accent-bold-edge)',
          500: 'var(--lc-accent)',
          600: 'var(--lc-accent)',
          700: 'var(--lc-accent-bold-edge)',
          800: 'var(--lc-accent-bold-edge)',
        },
        pink: {
          500: 'var(--lc-channel-instagram)',
          600: 'var(--lc-channel-instagram)',
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
